<script setup lang="ts">
/**
 * JournalEditorPage — Create or Edit a journal entry.
 *
 * - Saves to MySQL via POST /api/v1/journal (create) or PUT /api/v1/journal/{id} (edit)
 * - user_id is ALWAYS determined server-side; never sent from the frontend
 * - saved_at / updated_at is generated by the backend — never trusted from the browser
 * - Location uses browser Geolocation API only when the user explicitly requests it
 * - Mood picker uses Unicode emojis with accessible aria-labels
 * - Content is rendered as plain text (no v-html) — XSS-safe
 */

import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useRouter, useRoute, RouterLink, onBeforeRouteLeave } from 'vue-router'
import { useJournalStore } from '@/stores/journal'

const router = useRouter()
const route  = useRoute()
const store  = useJournalStore()

// ── Mode ─────────────────────────────────────────────────────────────────────
const entryId  = route.params.id as string | undefined
const isEditing = !!entryId

// ── Form state ────────────────────────────────────────────────────────────────
const title    = ref('')
const date     = ref(new Date().toISOString().split('T')[0])
const content  = ref('')
const tagInput = ref('')
const tags     = ref<string[]>([])

// Mood
const moodEmoji = ref('')
const moodLabel = ref('')
const showMoodPicker = ref(false)

// Location
const locationName   = ref('')
const latitude       = ref<number | null>(null)
const longitude      = ref<number | null>(null)
const locationSource = ref<'geolocation' | 'search' | 'manual' | null>(null)
const locationLoading = ref(false)
const locationError   = ref('')
const showLocationPicker = ref(false)
const manualLocationInput = ref('')

// Saving state
const saving     = ref(false)
const saveError  = ref('')
const saveSuccess = ref(false)
const isDirty    = ref(false)

// ── Load existing entry when editing ─────────────────────────────────────────
onMounted(async () => {
  if (isEditing && entryId) {
    // Find in store or fetch from API
    let existing = store.entries.find(e => e.id === entryId)
    if (!existing) {
      await store.fetchEntries()
      existing = store.entries.find(e => e.id === entryId)
    }
    if (existing) {
      title.value     = existing.title
      date.value      = existing.entry_date
      content.value   = existing.content
      moodEmoji.value = existing.mood_emoji ?? ''
      moodLabel.value = existing.mood_label ?? existing.mood ?? ''
      locationName.value = existing.location_name ?? ''
      latitude.value  = existing.latitude ?? null
      longitude.value = existing.longitude ?? null
      locationSource.value = existing.location_source ?? null
    }
  }
  // Watch for dirty state after loading
  setTimeout(() => { isDirty.value = false }, 50)
})

// ── Unsaved changes guard ─────────────────────────────────────────────────────
onBeforeRouteLeave((to, from, next) => {
  if (isDirty.value && !saveSuccess.value) {
    const confirmed = window.confirm(
      'You have unsaved changes. Leave without saving?'
    )
    if (confirmed) next()
    else next(false)
  } else {
    next()
  }
})

// Mark dirty when user types
function markDirty() { isDirty.value = true }

// ── Validation ────────────────────────────────────────────────────────────────
const canSave = computed(() =>
  title.value.trim().length > 0 &&
  content.value.trim().length > 0 &&
  date.value &&
  !saving.value
)

// ── Mood picker ───────────────────────────────────────────────────────────────
interface MoodCategory {
  name: string
  moods: { emoji: string; label: string }[]
}

const moodCategories: MoodCategory[] = [
  { name: 'Happy', moods: [
    { emoji: '😀', label: 'Grinning' },
    { emoji: '😃', label: 'Big smile' },
    { emoji: '😄', label: 'Laughing' },
    { emoji: '😁', label: 'Beaming' },
    { emoji: '😆', label: 'Grinning squinting' },
    { emoji: '🙂', label: 'Slightly smiling' },
    { emoji: '😊', label: 'Blushing smile' },
    { emoji: '😇', label: 'Innocent' },
  ]},
  { name: 'Loved', moods: [
    { emoji: '🥰', label: 'Smiling with hearts' },
    { emoji: '😍', label: 'Heart eyes' },
    { emoji: '😘', label: 'Blowing kiss' },
    { emoji: '❤️', label: 'Red heart' },
    { emoji: '🧡', label: 'Orange heart' },
    { emoji: '💛', label: 'Yellow heart' },
    { emoji: '💚', label: 'Green heart' },
    { emoji: '💙', label: 'Blue heart' },
    { emoji: '💜', label: 'Purple heart' },
  ]},
  { name: 'Calm', moods: [
    { emoji: '😌', label: 'Relieved' },
    { emoji: '🫶', label: 'Heart hands' },
    { emoji: '🌿', label: 'Peaceful' },
    { emoji: '☺️', label: 'Warm smile' },
    { emoji: '🌸', label: 'Gentle' },
    { emoji: '🕊️', label: 'At peace' },
  ]},
  { name: 'Excited', moods: [
    { emoji: '🤩', label: 'Star-struck' },
    { emoji: '🥳', label: 'Celebrating' },
    { emoji: '😎', label: 'Cool' },
    { emoji: '🚀', label: 'Energized' },
    { emoji: '🔥', label: 'Fired up' },
    { emoji: '✨', label: 'Sparkling' },
    { emoji: '⚡', label: 'Electric' },
  ]},
  { name: 'Nostalgic', moods: [
    { emoji: '🥹', label: 'Touched' },
    { emoji: '🥲', label: 'Happy-sad' },
    { emoji: '🌙', label: 'Nostalgic' },
    { emoji: '📷', label: 'Remembering' },
    { emoji: '🎞️', label: 'Old memories' },
  ]},
  { name: 'Grateful', moods: [
    { emoji: '🙏', label: 'Thankful' },
    { emoji: '🫶', label: 'Grateful' },
    { emoji: '💝', label: 'Deeply touched' },
    { emoji: '🌻', label: 'Warm gratitude' },
  ]},
  { name: 'Tired', moods: [
    { emoji: '😴', label: 'Sleeping' },
    { emoji: '🥱', label: 'Yawning' },
    { emoji: '😪', label: 'Sleepy' },
    { emoji: '😩', label: 'Weary' },
    { emoji: '😮‍💨', label: 'Exhausted' },
  ]},
  { name: 'Sad', moods: [
    { emoji: '😔', label: 'Pensive' },
    { emoji: '😞', label: 'Disappointed' },
    { emoji: '😢', label: 'Crying' },
    { emoji: '😭', label: 'Sobbing' },
    { emoji: '🥺', label: 'Pleading' },
    { emoji: '💔', label: 'Heartbroken' },
  ]},
  { name: 'Anxious', moods: [
    { emoji: '😰', label: 'Anxious sweat' },
    { emoji: '😟', label: 'Worried' },
    { emoji: '😬', label: 'Nervous' },
    { emoji: '😨', label: 'Fearful' },
    { emoji: '🫠', label: 'Melting stress' },
  ]},
  { name: 'Angry', moods: [
    { emoji: '😤', label: 'Steaming' },
    { emoji: '😠', label: 'Angry' },
    { emoji: '😡', label: 'Pouting' },
    { emoji: '🤬', label: 'Furious' },
  ]},
  { name: 'Confused', moods: [
    { emoji: '🤔', label: 'Thinking' },
    { emoji: '😐', label: 'Neutral' },
    { emoji: '😶', label: 'Speechless' },
    { emoji: '🫤', label: 'Uncertain' },
    { emoji: '🤷', label: 'Unsure' },
  ]},
]

function selectMood(emoji: string, label: string) {
  moodEmoji.value = emoji
  moodLabel.value = label
  showMoodPicker.value = false
  markDirty()
}

function clearMood() {
  moodEmoji.value = ''
  moodLabel.value = ''
}

// ── Location ──────────────────────────────────────────────────────────────────
function requestGeolocation() {
  if (!navigator.geolocation) {
    locationError.value = 'Geolocation is not supported by your browser.'
    return
  }
  locationLoading.value = true
  locationError.value   = ''

  navigator.geolocation.getCurrentPosition(
    async (position) => {
      latitude.value  = position.coords.latitude
      longitude.value = position.coords.longitude
      locationSource.value = 'geolocation'

      // Use Nominatim (OpenStreetMap) — no API key required, calls are proxied
      // or direct from browser (public endpoint, no auth needed)
      try {
        const res = await fetch(
          `https://nominatim.openstreetmap.org/reverse?lat=${latitude.value}&lon=${longitude.value}&format=json`,
          { headers: { 'Accept-Language': 'en' } }
        )
        const data = await res.json()
        const addr = data.address ?? {}
        const parts = [
          addr.suburb ?? addr.village ?? addr.town ?? addr.city_district,
          addr.city ?? addr.municipality,
          addr.state ?? addr.province,
        ].filter(Boolean)
        locationName.value = parts.length > 0 ? parts.join(', ') : data.display_name ?? 'Unknown location'
      } catch {
        locationName.value = `${latitude.value!.toFixed(4)}, ${longitude.value!.toFixed(4)}`
      }

      locationLoading.value = false
      showLocationPicker.value = false
      markDirty()
    },
    (err) => {
      locationLoading.value = false
      if (err.code === err.PERMISSION_DENIED) {
        locationError.value = 'Location permission denied. You can search for a location manually.'
      } else if (err.code === err.POSITION_UNAVAILABLE) {
        locationError.value = 'Location unavailable. Try searching manually.'
      } else {
        locationError.value = 'Location request timed out. Try searching manually.'
      }
    },
    { timeout: 10000, maximumAge: 60000 }
  )
}

async function searchLocation() {
  if (!manualLocationInput.value.trim()) return
  locationLoading.value = true
  locationError.value   = ''
  try {
    const res = await fetch(
      `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(manualLocationInput.value)}&format=json&limit=1`,
      { headers: { 'Accept-Language': 'en' } }
    )
    const results = await res.json()
    if (results.length > 0) {
      const r = results[0]
      latitude.value  = parseFloat(r.lat)
      longitude.value = parseFloat(r.lon)
      locationName.value   = r.display_name
      locationSource.value = 'search'
      showLocationPicker.value = false
      markDirty()
    } else {
      locationError.value = 'No results found. Try a different search term.'
    }
  } catch {
    locationError.value = 'Search failed. Please try again.'
  } finally {
    locationLoading.value = false
  }
}

function setManualLocation() {
  if (!manualLocationInput.value.trim()) return
  locationName.value   = manualLocationInput.value.trim()
  latitude.value       = null
  longitude.value      = null
  locationSource.value = 'manual'
  showLocationPicker.value = false
  manualLocationInput.value = ''
  markDirty()
}

function clearLocation() {
  locationName.value   = ''
  latitude.value       = null
  longitude.value      = null
  locationSource.value = null
  locationError.value  = ''
  markDirty()
}

// ── Tags ──────────────────────────────────────────────────────────────────────
function addTag() {
  const t = tagInput.value.trim().replace(/,/g, '')
  if (t && !tags.value.includes(t) && tags.value.length < 10) {
    tags.value.push(t)
    markDirty()
  }
  tagInput.value = ''
}

function removeTag(tag: string) {
  tags.value = tags.value.filter(t => t !== tag)
  markDirty()
}

function handleTagKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' || e.key === ',') {
    e.preventDefault()
    addTag()
  }
}

// ── Save ──────────────────────────────────────────────────────────────────────
async function handleSave() {
  if (!canSave.value) return
  saving.value   = true
  saveError.value = ''

  const payload = {
    title:            title.value.trim(),
    content:          content.value.trim(),
    entry_date:       date.value,
    mood_emoji:       moodEmoji.value || null,
    mood_label:       moodLabel.value || null,
    // Keep legacy mood field null for custom emoji moods
    mood:             null as string | null,
    location_name:    locationName.value || null,
    latitude:         latitude.value,
    longitude:        longitude.value,
    location_source:  locationSource.value,
    visibility:       'private',
  }

  try {
    if (isEditing && entryId) {
      await store.updateEntry(entryId, payload)
    } else {
      await store.createEntry(payload as Parameters<typeof store.createEntry>[0])
    }
    saveSuccess.value = true
    isDirty.value     = false
    await router.push({ name: 'journal' })
  } catch (err: unknown) {
    const e = err as { response?: { status?: number; data?: { message?: string; errors?: Record<string, string[]> } } }
    const status = e?.response?.status
    const data   = e?.response?.data
    if (status === 422 && data?.errors) {
      const firstError = Object.values(data.errors)[0]?.[0]
      saveError.value = firstError ?? 'Please check the highlighted fields.'
    } else if (!e?.response) {
      saveError.value = `You're currently offline or the server is unavailable.`
    } else {
      saveError.value = data?.message ?? `We couldn't save your journal entry right now. Please try again.`
    }
  } finally {
    saving.value = false
  }
}

// Close pickers when clicking outside
function closePickers() {
  showMoodPicker.value     = false
  showLocationPicker.value = false
}
</script>

<template>
  <div class="min-h-screen bg-[#f5ebdd]" @click.self="closePickers">

    <!-- Header -->
    <div class="bg-[#fdfaf5] border-b border-[#e5d4bb] sticky top-0 z-10">
      <div class="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between gap-4">
        <RouterLink :to="{ name: 'journal' }" class="inline-flex items-center gap-1.5 text-sm text-[#8a5c2e] hover:text-[#7B0323] transition-colors" :class="{ 'pointer-events-none opacity-50': saving }">
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
          </svg>
          Journal
        </RouterLink>

        <div class="flex items-center gap-2">
          <!-- Save error inline -->
          <p v-if="saveError" role="alert" class="text-xs text-[#7B0323] max-w-xs text-right">{{ saveError }}</p>

          <button
            type="button"
            :disabled="!canSave"
            :aria-busy="saving"
            :class="[
              'inline-flex items-center gap-2 text-sm font-semibold px-5 py-2.5 rounded border transition-all',
              canSave
                ? 'bg-[#7B0323] text-[#fdfaf5] border-[#5a0019] hover:bg-[#5a0019]'
                : 'bg-[#d7c7b3] text-[#fdfaf5] border-[#d7c7b3] cursor-not-allowed opacity-60',
            ]"
            @click="handleSave"
          >
            <svg v-if="saving" class="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24" aria-hidden="true">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
            </svg>
            {{ saving ? 'Saving…' : (isEditing ? 'Save Changes' : 'Save Entry') }}
          </button>
        </div>
      </div>
    </div>

    <!-- Form -->
    <div class="max-w-3xl mx-auto px-4 sm:px-6 py-8 flex flex-col gap-6">

      <!-- Hero text -->
      <div>
        <p class="text-xs font-semibold uppercase tracking-widest text-[#8a5c2e] mb-1">
          {{ isEditing ? 'Edit entry' : 'New entry' }}
        </p>
        <p class="text-sm text-[#6b4423]">Write something worth remembering.</p>
      </div>

      <!-- Title -->
      <div>
        <label for="entry-title" class="block text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-1.5">
          Title <span class="text-[#7B0323]" aria-label="required">*</span>
        </label>
        <input
          id="entry-title"
          v-model="title"
          type="text"
          placeholder="What should you call this memory?"
          autocomplete="off"
          class="w-full px-3 py-3 bg-[#fdfaf5] border border-[#d7c7b3] rounded text-[#2b1a10] placeholder:text-[#a68e73] focus:outline-none focus:border-[#7B0323] focus:ring-2 focus:ring-[#7B0323]/10 transition"
          style="font-family:'Playfair Display',Georgia,serif; font-size:1.1rem;"
          @input="markDirty"
        />
      </div>

      <!-- Date + Mood row -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">

        <!-- Date -->
        <div>
          <label for="entry-date" class="block text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-1.5">
            Date <span class="text-[#7B0323]" aria-label="required">*</span>
          </label>
          <input
            id="entry-date"
            v-model="date"
            type="date"
            class="w-full px-3 py-2.5 bg-[#fdfaf5] border border-[#d7c7b3] rounded text-sm text-[#2b1a10] focus:outline-none focus:border-[#7B0323] focus:ring-2 focus:ring-[#7B0323]/10 transition"
            @change="markDirty"
          />
        </div>

        <!-- Mood -->
        <div class="relative">
          <p class="block text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-1.5">
            How are you feeling?
          </p>
          <button
            type="button"
            aria-haspopup="dialog"
            :aria-expanded="showMoodPicker"
            aria-label="Select mood"
            class="w-full flex items-center gap-2 px-3 py-2.5 bg-[#fdfaf5] border border-[#d7c7b3] rounded text-sm text-left transition hover:border-[#7B0323]"
            @click.stop="showMoodPicker = !showMoodPicker; showLocationPicker = false"
          >
            <span v-if="moodEmoji" class="text-xl leading-none" aria-hidden="true">{{ moodEmoji }}</span>
            <span :class="moodLabel ? 'text-[#2b1a10]' : 'text-[#a68e73]'">
              {{ moodLabel || 'Select mood' }}
            </span>
            <button
              v-if="moodEmoji"
              type="button"
              aria-label="Clear mood"
              class="ml-auto text-[#c4ad94] hover:text-[#7B0323]"
              @click.stop="clearMood"
            >
              <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>
            </button>
          </button>

          <!-- Mood picker popover -->
          <div
            v-if="showMoodPicker"
            role="dialog"
            aria-label="Mood selector"
            class="absolute z-30 top-full left-0 mt-1 w-full sm:w-96 bg-[#fdfaf5] border border-[#d7c7b3] rounded shadow-lg max-h-72 overflow-y-auto"
            @click.stop
          >
            <div class="px-3 py-2 border-b border-[#efe2cf] flex items-center justify-between">
              <p class="text-xs font-semibold uppercase tracking-wider text-[#6b4423]">How are you feeling?</p>
              <button type="button" aria-label="Close mood picker" class="text-[#a68e73] hover:text-[#2b1a10]" @click="showMoodPicker = false">
                <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div class="p-3 flex flex-col gap-3">
              <div v-for="cat in moodCategories" :key="cat.name">
                <p class="text-xs font-semibold uppercase tracking-wider text-[#a68e73] mb-1.5">{{ cat.name }}</p>
                <div class="flex flex-wrap gap-1">
                  <button
                    v-for="m in cat.moods"
                    :key="m.emoji"
                    type="button"
                    :aria-label="`${m.label} mood`"
                    :aria-pressed="moodEmoji === m.emoji"
                    :class="[
                      'text-2xl w-10 h-10 flex items-center justify-center rounded transition hover:bg-[#f5ebdd]',
                      moodEmoji === m.emoji ? 'bg-[#f5ebdd] ring-2 ring-[#7B0323]' : '',
                    ]"
                    @click="selectMood(m.emoji, m.label)"
                  >
                    {{ m.emoji }}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Location -->
      <div class="relative">
        <p class="block text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-1.5">
          Where were you? <span class="normal-case font-normal text-[#a68e73]">(optional)</span>
        </p>

        <!-- Location selected -->
        <div v-if="locationName" class="flex items-center gap-2 px-3 py-2.5 bg-[#fdfaf5] border border-[#d7c7b3] rounded text-sm text-[#2b1a10]">
          <svg class="w-4 h-4 text-[#7B0323] shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z"/>
          </svg>
          <span class="flex-1 truncate">{{ locationName }}</span>
          <button type="button" aria-label="Change location" class="text-xs font-medium text-[#7B0323] hover:underline shrink-0" @click.stop="showLocationPicker = true">
            Change
          </button>
          <button type="button" aria-label="Remove location" class="text-[#c4ad94] hover:text-[#7B0323]" @click="clearLocation">
            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Add location button -->
        <button
          v-else
          type="button"
          aria-label="Add location"
          class="w-full flex items-center gap-2 px-3 py-2.5 bg-[#fdfaf5] border border-dashed border-[#d7c7b3] rounded text-sm text-[#a68e73] hover:border-[#7B0323] hover:text-[#7B0323] transition"
          @click.stop="showLocationPicker = !showLocationPicker; showMoodPicker = false"
        >
          <svg class="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z"/>
          </svg>
          📍 Add Location
        </button>

        <!-- Location picker popover -->
        <div
          v-if="showLocationPicker"
          role="dialog"
          aria-label="Location picker"
          class="absolute z-30 top-full left-0 mt-1 w-full bg-[#fdfaf5] border border-[#d7c7b3] rounded shadow-lg"
          @click.stop
        >
          <div class="px-4 py-3">
            <p class="text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-3">Add your location</p>

            <!-- Error -->
            <p v-if="locationError" role="alert" class="text-xs text-[#7B0323] mb-3 bg-[#fdf2f3] border border-[#eeaab5] px-3 py-2 rounded">
              {{ locationError }}
            </p>

            <!-- Use my location -->
            <button
              type="button"
              :disabled="locationLoading"
              class="w-full flex items-center gap-2 px-4 py-3 bg-[#f5ebdd] border border-[#d7c7b3] rounded text-sm font-medium text-[#2b1a10] hover:border-[#7B0323] hover:text-[#7B0323] transition mb-2 disabled:opacity-50"
              @click="requestGeolocation"
            >
              <svg class="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z"/>
              </svg>
              <span v-if="locationLoading">Getting your location…</span>
              <span v-else>Use My Current Location</span>
              <svg v-if="locationLoading" class="w-4 h-4 animate-spin ml-auto" fill="none" viewBox="0 0 24 24" aria-hidden="true">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
              </svg>
            </button>
            <p class="text-xs text-[#a68e73] mb-3">Cronevia uses your location only to save where this memory happened. Permission is requested only when you choose this option.</p>

            <!-- Search location -->
            <div class="flex gap-2 mb-2">
              <input
                v-model="manualLocationInput"
                type="text"
                placeholder="Search for a place…"
                aria-label="Search location"
                class="flex-1 px-3 py-2.5 text-sm bg-[#fdfaf5] border border-[#d7c7b3] rounded text-[#2b1a10] placeholder:text-[#a68e73] focus:outline-none focus:border-[#7B0323] focus:ring-2 focus:ring-[#7B0323]/10 transition"
                @keydown.enter="searchLocation"
              />
              <button
                type="button"
                :disabled="locationLoading || !manualLocationInput.trim()"
                class="px-4 py-2.5 text-sm font-semibold bg-[#7B0323] text-[#fdfaf5] border border-[#5a0019] rounded hover:bg-[#5a0019] transition disabled:opacity-50"
                @click="searchLocation"
              >
                Search
              </button>
            </div>
            <button
              type="button"
              class="text-xs text-[#8a5c2e] hover:text-[#7B0323] hover:underline"
              @click="setManualLocation"
            >
              Or just type a location name →
            </button>

            <button
              type="button"
              class="w-full mt-3 text-center text-xs text-[#a68e73] hover:text-[#2b1a10] py-2"
              @click="showLocationPicker = false; locationError = ''"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>

      <!-- Content -->
      <div>
        <label for="entry-content" class="block text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-1.5">
          Your story <span class="text-[#7B0323]" aria-label="required">*</span>
        </label>
        <textarea
          id="entry-content"
          v-model="content"
          rows="14"
          placeholder="Start writing…"
          aria-describedby="content-counter"
          class="w-full px-4 py-3.5 bg-[#fdfaf5] border border-[#d7c7b3] rounded text-[#2b1a10] text-sm leading-relaxed placeholder:text-[#a68e73] focus:outline-none focus:border-[#7B0323] focus:ring-2 focus:ring-[#7B0323]/10 transition resize-y"
          style="min-height: 260px; line-height: 1.8;"
          @input="markDirty"
        />
        <p id="content-counter" class="text-xs text-right mt-1" :class="content.length > 9000 ? 'text-[#7B0323]' : 'text-[#a68e73]'">
          {{ content.length.toLocaleString() }} / 10,000
        </p>
      </div>

      <!-- Tags -->
      <div>
        <p class="text-xs font-semibold uppercase tracking-wider text-[#6b4423] mb-2">
          Tags <span class="normal-case font-normal text-[#a68e73]">(optional)</span>
        </p>
        <div class="flex flex-wrap gap-2 mb-2" role="list" aria-label="Selected tags">
          <span
            v-for="tag in tags"
            :key="tag"
            role="listitem"
            class="inline-flex items-center gap-1.5 text-xs px-2.5 py-1 bg-[#f5ebdd] border border-[#d7c7b3] rounded text-[#8a5c2e] font-medium"
          >
            {{ tag }}
            <button type="button" :aria-label="`Remove tag ${tag}`" class="text-[#c4ad94] hover:text-[#7B0323]" @click="removeTag(tag)">
              <svg class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>
            </button>
          </span>
        </div>
        <input
          v-model="tagInput"
          type="text"
          placeholder="Add a tag, press Enter…"
          aria-label="Add tag"
          class="max-w-xs px-3 py-2 text-sm bg-[#fdfaf5] border border-[#d7c7b3] rounded text-[#2b1a10] placeholder:text-[#a68e73] focus:outline-none focus:border-[#7B0323] focus:ring-2 focus:ring-[#7B0323]/10 transition"
          @keydown="handleTagKeydown"
          @blur="addTag"
        />
      </div>

      <!-- Save button (bottom of form, mobile-friendly) -->
      <div class="pt-2">
        <button
          type="button"
          :disabled="!canSave"
          :aria-busy="saving"
          :class="[
            'w-full sm:w-auto inline-flex items-center justify-center gap-2 text-sm font-semibold px-8 py-3.5 rounded border transition-all',
            canSave
              ? 'bg-[#7B0323] text-[#fdfaf5] border-[#5a0019] hover:bg-[#5a0019]'
              : 'bg-[#d7c7b3] text-[#fdfaf5] border-[#d7c7b3] cursor-not-allowed opacity-60',
          ]"
          @click="handleSave"
        >
          <svg v-if="saving" class="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24" aria-hidden="true">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
          </svg>
          {{ saving ? 'Saving…' : (isEditing ? 'Save Changes' : 'Save Entry') }}
        </button>
        <p v-if="saveError" role="alert" class="mt-2 text-xs text-[#7B0323]">{{ saveError }}</p>
      </div>
    </div>
  </div>
</template>
